apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managementrepos.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: ManagementRepo
    listKind: ManagementRepoList
    plural: managementrepos
    singular: managementrepo
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
